[theme]
primaryColor = "#ff8c00"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#c0c0c0"
font = "monospace"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
